In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

import warnings
warnings.filterwarnings('ignore') 

from sklearn.linear_model import LogisticRegression

from statsmodels.api import Logit 

In [2]:
df = pd.read_excel('Cellphone (2).xlsx') 
df.head() 

Churn  AccountWeeks  ContractRenewal  DataPlan  DataUsage  CustServCalls  \
0      1         108.0              0.0       0.0       0.38            2.0   
1      0         113.0              1.0       1.0       3.59            1.0   
2      0         101.0              1.0       0.0       0.00            0.0   
3      0          80.0              1.0       1.0       2.89            4.0   
4      0          70.0              1.0       0.0       0.00            0.0   

   DayMins  DayCalls  MonthlyCharge  OverageFee  RoamMins  
0    115.1     114.0           41.8       10.57      13.8  
1     44.9      63.0           55.9        6.71      13.3  
2    257.3      84.0           60.0        9.24      13.5  
3    166.4      92.0           77.9       11.92      10.7  
4    175.4     130.0           44.0        7.98      11.6

In [15]:
df.isnull().sum()*100/len(df) 

Churn              0.000000
AccountWeeks       0.900090
ContractRenewal    0.540054
DataPlan           0.270027
DataUsage          0.480048
CustServCalls      1.560156
DayMins            1.050105
DayCalls           0.330033
MonthlyCharge      0.390039
OverageFee         0.720072
RoamMins           0.210021
dtype: float64

In [16]:
df.dropna(axis=0,inplace=True) 

In [17]:
df.info()  

<class 'pandas.core.frame.DataFrame'>
Index: 3196 entries, 0 to 3332
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Churn            3196 non-null   int64  
 1   AccountWeeks     3196 non-null   float64
 2   ContractRenewal  3196 non-null   float64
 3   DataPlan         3196 non-null   float64
 4   DataUsage        3196 non-null   float64
 5   CustServCalls    3196 non-null   float64
 6   DayMins          3196 non-null   float64
 7   DayCalls         3196 non-null   float64
 8   MonthlyCharge    3196 non-null   float64
 9   OverageFee       3196 non-null   float64
 10  RoamMins         3196 non-null   float64
dtypes: float64(10), int64(1)
memory usage: 299.6 KB


In [19]:
from statsmodels.api import Logit 

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
X=df.drop("Churn",axis=1) 
y=df["Churn"] 

In [22]:
from sklearn.model_selection import train_test_split 

In [23]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=100) 

In [24]:
x_train

AccountWeeks  ContractRenewal  DataPlan  DataUsage  CustServCalls  \
1311         105.0              1.0       1.0       2.62            2.0   
2387          18.0              1.0       0.0       0.27            3.0   
1563         111.0              1.0       0.0       0.00            4.0   
2504         162.0              1.0       0.0       0.33            2.0   
110           86.0              1.0       1.0       2.73            0.0   
...            ...              ...       ...        ...            ...   
2020          63.0              1.0       0.0       0.37            0.0   
85           118.0              1.0       0.0       0.00            2.0   
1946          72.0              1.0       0.0       0.27            0.0   
2965          62.0              1.0       0.0       0.00            2.0   
1620         146.0              1.0       0.0       0.00            3.0   

      DayMins  DayCalls  MonthlyCharge  OverageFee  RoamMins  
1311     88.1     125.0           56.2        8.80       9.7  
2387    197.0      97.0           53.7       10.19       8.7  
1563    176.9     128.0           39.0        5.14      10.5  
2504    217.6      87.0           64.3       13.95      10.4  
110     197.9      99.0           75.3        8.28      10.1  
...       ...       ...            ...         ...       ...  
2020    211.2      80.0           60.7       11.89      12.3  
85      253.2     122.0           61.0       10.05       9.7  
1946    272.4      88.0           58.7        5.40      12.7  
2965     86.3      84.0           35.0       11.94      12.5  
1620    195.9      86.0           53.0       11.43      12.2  

[2237 rows x 10 columns]

In [25]:
model=LogisticRegression(solver="newton-cg",max_iter=10000,n_jobs=-1) 

In [26]:
model.fit(x_train,y_train) 

LogisticRegression(max_iter=10000, n_jobs=-1, solver='newton-cg')

In [29]:
prd=model.predict(x_test) 


In [30]:
pd.DataFrame(model.predict_proba(x_test))

0         1
0    0.848820  0.151180
1    0.975918  0.024082
2    0.859715  0.140285
3    0.867425  0.132575
4    0.876507  0.123493
..        ...       ...
954  0.990905  0.009095
955  0.936140  0.063860
956  0.787722  0.212278
957  0.744808  0.255192
958  0.771222  0.228778

[959 rows x 2 columns]

In [31]:
from sklearn import metrics 

In [32]:
metrics.confusion_matrix(y_test,prd) 

array([[791,  20],
       [122,  26]], dtype=int64)

In [33]:
print(metrics.classification_report(y_test,prd)) 

              precision    recall  f1-score   support

           0       0.87      0.98      0.92       811
           1       0.57      0.18      0.27       148

    accuracy                           0.85       959
   macro avg       0.72      0.58      0.59       959
weighted avg       0.82      0.85      0.82       959



In [34]:
model=LogisticRegression(solver='newton-cg',max_iter=10000,n_jobs=-1,class_weight={0:0.18,1:0.98}) 

In [38]:
model.fit(x_train,y_train)  

LogisticRegression(class_weight={0: 0.18, 1: 0.98}, max_iter=10000, n_jobs=-1,
                   solver='newton-cg')

In [39]:
prd=model.predict(x_test) 

In [40]:
pd.DataFrame(model.predict_proba(x_test)) 

0         1
0    0.574554  0.425446
1    0.889568  0.110432
2    0.585237  0.414763
3    0.496140  0.503860
4    0.567836  0.432164
..        ...       ...
954  0.966407  0.033593
955  0.760731  0.239269
956  0.408769  0.591231
957  0.362745  0.637255
958  0.368295  0.631705

[959 rows x 2 columns]

In [41]:
metrics.confusion_matrix(y_test,prd)  #After class balance

array([[622, 189],
       [ 38, 110]], dtype=int64)

In [42]:
print(metrics.classification_report(y_test,prd)) 

              precision    recall  f1-score   support

           0       0.94      0.77      0.85       811
           1       0.37      0.74      0.49       148

    accuracy                           0.76       959
   macro avg       0.66      0.76      0.67       959
weighted avg       0.85      0.76      0.79       959



In [43]:
prd_tst=model.predict(x_train) 

In [45]:
print(metrics.classification_report(y_train,prd_tst))  #train Classification.report 

              precision    recall  f1-score   support

           0       0.95      0.80      0.87      1920
           1       0.38      0.74      0.50       317

    accuracy                           0.79      2237
   macro avg       0.66      0.77      0.68      2237
weighted avg       0.87      0.79      0.82      2237



In [46]:
model.intercept_ 

array([-3.72247991])

In [50]:
model.coef_ 

array([[ 1.62501227e-03, -2.15225569e+00, -9.49766629e-01,
         9.01612912e-02,  6.11240389e-01,  1.41211062e-02,
         1.00392108e-03, -6.53909471e-03,  1.30558643e-01,
         4.85141205e-02]])

In [5]:
X = df.drop('Churn', axis=1)
y = df['Churn']  

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.3)

In [20]:
model = LogisticRegression(solver='newton-cg', max_iter=10000, n_jobs=-1, 
                              class_weight={0: 0.15, 1: 0.85})

In [21]:
model.fit(x_train, y_train)

LogisticRegression(class_weight={0: 0.15, 1: 0.85}, max_iter=10000, n_jobs=-1,
                   solver='newton-cg')

In [22]:
pred = model.predict(x_test)    # Class Prediction
pred

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,

In [23]:
pd.DataFrame(model.predict_proba(x_test))

0         1
0    0.725022  0.274978
1    0.763562  0.236438
2    0.823628  0.176372
3    0.517163  0.482837
4    0.310441  0.689559
..        ...       ...
995  0.766316  0.233684
996  0.683250  0.316750
997  0.784996  0.215004
998  0.839903  0.160097
999  0.771042  0.228958

[1000 rows x 2 columns]

In [24]:
from sklearn import metrics

In [16]:
metrics.confusion_matrix(y_test, pred)    # Original Data

array([[835,  12],
       [135,  18]], dtype=int64)

In [25]:
metrics.confusion_matrix(y_test, pred)   # After Class Balance

array([[673, 174],
       [ 38, 115]], dtype=int64)

In [17]:
# Accuracy
# Recall (0, 1)
# Precision (0, 1)

print(metrics.classification_report(y_test, pred))    # Original Data

              precision    recall  f1-score   support

           0       0.86      0.99      0.92       847
           1       0.60      0.12      0.20       153

    accuracy                           0.85      1000
   macro avg       0.73      0.55      0.56      1000
weighted avg       0.82      0.85      0.81      1000



In [26]:
print(metrics.classification_report(y_test, pred))   # Class Balance

              precision    recall  f1-score   support

           0       0.95      0.79      0.86       847
           1       0.40      0.75      0.52       153

    accuracy                           0.79      1000
   macro avg       0.67      0.77      0.69      1000
weighted avg       0.86      0.79      0.81      1000



In [18]:
pred_train = model.predict(x_train)
print(metrics.classification_report(y_train, pred_train))

              precision    recall  f1-score   support

           0       0.88      0.98      0.93      2003
           1       0.56      0.17      0.26       330

    accuracy                           0.86      2333
   macro avg       0.72      0.58      0.59      2333
weighted avg       0.83      0.86      0.83      2333



In [19]:
df['Churn'].value_counts(normalize=True)

Churn
0    0.855086
1    0.144914
Name: proportion, dtype: float64

In [27]:
model.coef_

array([[ 1.41566821e-03, -2.03706139e+00, -8.64711198e-01,
        -3.03013149e-01,  5.51632671e-01,  6.10131826e-03,
         1.58255321e-03,  3.68160615e-02,  6.39014349e-02,
         5.75230016e-02]])

In [29]:
model.intercept_

array([-3.82044135])

In [31]:
from statsmodels.api import add_constant
X = add_constant(X)

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [32]:
logit = Logit(y_train, x_train.astype('float')).fit()
logit.summary()

Optimization terminated successfully.
         Current function value: 0.326432
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                  Churn   No. Observations:                 2333
Model:                          Logit   Df Residuals:                     2322
Method:                           MLE   Df Model:                           10
Date:                Wed, 31 Jan 2024   Pseudo R-squ.:                  0.1991
Time:                        20:15:40   Log-Likelihood:                -761.57
converged:                       True   LL-Null:                       -950.90
Covariance Type:            nonrobust   LLR p-value:                 3.262e-75
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              -5.7718      0.646     -8.932      0.000      -7.038      -4.505
AccountWeeks        0.0010      0.002      0.624      0.533      -0.002       0.004
ContractRenewal    -1.8768      0.168    -11.178      0.000      -2.206      -1.548
DataPlan           -1.6390      0.624     -2.626      0.009      -2.862      -0.416
DataUsage          -0.2789      0.301     -0.926      0.354      -0.869       0.311
CustServCalls       0.4847      0.046     10.463      0.000       0.394       0.575
DayMins             0.0029      0.006      0.498      0.618      -0.009       0.014
DayCalls            0.0023      0.003      0.706      0.480      -0.004       0.009
MonthlyCharge       0.0565      0.034      1.680      0.093      -0.009       0.123
OverageFee          0.0432      0.064      0.679      0.497      -0.081       0.168
RoamMins            0.0592      0.026      2.269      0.023       0.008       0.110
===================================================================================
"""

In [34]:
x_train1 = x_train.drop('DayMins', axis=1)
logit = Logit(y_train, x_train1.astype('float')).fit()
logit.summary()

Optimization terminated successfully.
         Current function value: 0.326487
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                  Churn   No. Observations:                 2333
Model:                          Logit   Df Residuals:                     2323
Method:                           MLE   Df Model:                            9
Date:                Wed, 31 Jan 2024   Pseudo R-squ.:                  0.1990
Time:                        20:17:43   Log-Likelihood:                -761.69
converged:                       True   LL-Null:                       -950.90
Covariance Type:            nonrobust   LLR p-value:                 5.533e-76
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              -5.7171      0.636     -8.992      0.000      -6.963      -4.471
AccountWeeks        0.0010      0.002      0.619      0.536      -0.002       0.004
ContractRenewal    -1.8781      0.168    -11.190      0.000      -2.207      -1.549
DataPlan           -1.7937      0.544     -3.295      0.001      -2.861      -0.727
DataUsage          -0.3910      0.188     -2.080      0.038      -0.759      -0.023
CustServCalls       0.4857      0.046     10.494      0.000       0.395       0.576
DayCalls            0.0023      0.003      0.703      0.482      -0.004       0.009
MonthlyCharge       0.0729      0.007      9.889      0.000       0.058       0.087
OverageFee          0.0150      0.029      0.518      0.605      -0.042       0.072
RoamMins            0.0560      0.025      2.218      0.027       0.007       0.105
===================================================================================
"""

In [35]:
x_train2 = x_train1.drop('OverageFee', axis=1)
logit = Logit(y_train, x_train2.astype('float')).fit()
logit.summary()

Optimization terminated successfully.
         Current function value: 0.326545
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                  Churn   No. Observations:                 2333
Model:                          Logit   Df Residuals:                     2324
Method:                           MLE   Df Model:                            8
Date:                Wed, 31 Jan 2024   Pseudo R-squ.:                  0.1988
Time:                        20:18:16   Log-Likelihood:                -761.83
converged:                       True   LL-Null:                       -950.90
Covariance Type:            nonrobust   LLR p-value:                 8.873e-77
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              -5.6250      0.610     -9.228      0.000      -6.820      -4.430
AccountWeeks        0.0010      0.002      0.605      0.545      -0.002       0.004
ContractRenewal    -1.8753      0.168    -11.181      0.000      -2.204      -1.547
DataPlan           -1.8005      0.544     -3.308      0.001      -2.867      -0.734
DataUsage          -0.4019      0.187     -2.153      0.031      -0.768      -0.036
CustServCalls       0.4850      0.046     10.486      0.000       0.394       0.576
DayCalls            0.0023      0.003      0.692      0.489      -0.004       0.009
MonthlyCharge       0.0743      0.007     10.906      0.000       0.061       0.088
RoamMins            0.0554      0.025      2.197      0.028       0.006       0.105
===================================================================================
"""

In [36]:
x_train3 = x_train2.drop('AccountWeeks', axis=1)
logit = Logit(y_train, x_train3.astype('float')).fit()
logit.summary()

Optimization terminated successfully.
         Current function value: 0.326623
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                  Churn   No. Observations:                 2333
Model:                          Logit   Df Residuals:                     2325
Method:                           MLE   Df Model:                            7
Date:                Wed, 31 Jan 2024   Pseudo R-squ.:                  0.1986
Time:                        20:18:39   Log-Likelihood:                -762.01
converged:                       True   LL-Null:                       -950.90
Covariance Type:            nonrobust   LLR p-value:                 1.392e-77
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              -5.5214      0.584     -9.451      0.000      -6.666      -4.376
ContractRenewal    -1.8795      0.168    -11.215      0.000      -2.208      -1.551
DataPlan           -1.7965      0.544     -3.301      0.001      -2.863      -0.730
DataUsage          -0.4022      0.187     -2.153      0.031      -0.768      -0.036
CustServCalls       0.4860      0.046     10.512      0.000       0.395       0.577
DayCalls            0.0023      0.003      0.701      0.483      -0.004       0.009
MonthlyCharge       0.0743      0.007     10.907      0.000       0.061       0.088
RoamMins            0.0553      0.025      2.194      0.028       0.006       0.105
===================================================================================
"""

In [38]:
x_train4 = x_train3.drop('DayCalls', axis=1)
logit = Logit(y_train, x_train4.astype('float')).fit()
logit.summary()

Optimization terminated successfully.
         Current function value: 0.326728
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                  Churn   No. Observations:                 2333
Model:                          Logit   Df Residuals:                     2326
Method:                           MLE   Df Model:                            6
Date:                Wed, 31 Jan 2024   Pseudo R-squ.:                  0.1984
Time:                        20:19:10   Log-Likelihood:                -762.26
converged:                       True   LL-Null:                       -950.90
Covariance Type:            nonrobust   LLR p-value:                 2.141e-78
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              -5.2889      0.479    -11.042      0.000      -6.228      -4.350
ContractRenewal    -1.8785      0.168    -11.207      0.000      -2.207      -1.550
DataPlan           -1.7939      0.544     -3.299      0.001      -2.860      -0.728
DataUsage          -0.4037      0.187     -2.163      0.031      -0.769      -0.038
CustServCalls       0.4852      0.046     10.507      0.000       0.395       0.576
MonthlyCharge       0.0743      0.007     10.902      0.000       0.061       0.088
RoamMins            0.0555      0.025      2.203      0.028       0.006       0.105
===================================================================================
"""

In [39]:
logit.fittedvalues

2016   -2.379205
1362    0.122654
2670   -1.037968
2210   -0.220428
1846   -3.087209
          ...   
1095   -3.776001
1130   -0.185307
1294   -3.850937
860    -0.275230
3174   -2.755804
Length: 2333, dtype: float64

In [42]:
pred_train = np.where(logit.predict(x_train4)>0.5, 1, 0)

In [43]:
x_test1 = x_test.drop(['DayMins', 'DayCalls', 'OverageFee', 'AccountWeeks'], axis=1)

In [45]:
pred_test = np.where(logit.predict(x_test1) > 0.5, 1, 0)

In [46]:
print(metrics.classification_report(y_train, pred_train))
print(metrics.classification_report(y_test, pred_test))

              precision    recall  f1-score   support

           0       0.88      0.98      0.92      2003
           1       0.55      0.17      0.26       330

    accuracy                           0.86      2333
   macro avg       0.72      0.57      0.59      2333
weighted avg       0.83      0.86      0.83      2333

              precision    recall  f1-score   support

           0       0.86      0.99      0.92       847
           1       0.66      0.14      0.23       153

    accuracy                           0.86      1000
   macro avg       0.76      0.56      0.57      1000
weighted avg       0.83      0.86      0.82      1000

